
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace QuanLyKhachSan._2._1
{
    public partial class DanhsachHD : DevExpress.XtraEditors.XtraForm
    {
        public DanhsachHD()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            chI_TIET_HOA_DONTableAdapter1.Fill(qlksDataSet1.CHI_TIET_HOA_DON);
        }

        private void DanhsachHD_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'qLKSDataSet.CHI_TIET_HOA_DON' table. You can move, or remove it, as needed.
            this.cHI_TIET_HOA_DONTableAdapter.Fill(this.qLKSDataSet.CHI_TIET_HOA_DON);

        }

        private void btnRefresh_Click(object sender, EventArgs e)
        {

        }

        private void btnThoat_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}